packages/githon/lib/githon.js
packages/githon/lib/plugins/__tests__/validatePlugin.js
packages/githon/lib/plugins/validatePlugin.js

fix(githon): relax "gitbook" engine version check

---

package.json
packages/@githon/asciidoc/package.json
packages/@githon/html/package.json
packages/@githon/markdown/package.json
packages/@githon/markup-it/package.json
packages/githon/package.json

chore: add "clean" command

---

docs/config.md
packages/honkit/src/constants/configSchema.js
packages/honkit/src/output/ebook/getConvertOptions.js

Closes #27 
(straight port of https://github.com/GitbookIO/gitbook/pull/1445)

feat(ebook): embed PDF fonts

---

tsconfig.json

- Made changes in compilerOptions targeted javascript
Issue reference: #66

pref(tsconfig.json) : change typescript configuration

---

.github/workflows/test.yml

feat(ci): add Node 10 to test matrix

---

packages/honkit/bin/honkit.js

Closes #73
Adds `--version` option using commander `.version`

feat(cli): --version option

---

README.md
docs/setup.md

docs: add warning about globally and locally

---

docs/themes/README.md
packages/@honkit/theme-default/package.json

It will fix `styles/website.css` loading
fix https://github.com/honkit/honkit/issues/89

fix(theme-default): include `index.js` to `files`

---

README.md
docs/examples.md

docs(examples): add examples page

---

docs/templating/variables.md

~have to update `packages/honkit/src/__tests__/__fixtures__/honkit/docs/templating/variables.md`~

docs: support `honkit` variables #36

---

docker/Dockerfile
docker/README.md

feat(docker): add ebook-convert installation

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/book/CHANGELOG.md
examples/book/package.json
lerna.json
packages/@honkit/theme-default/CHANGELOG.md
packages/@honkit/theme-default/package.json
packages/honkit/CHANGELOG.md
packages/honkit/package.json

- **theme-default**: support `honkit` variablbles #36 
- **docker**: support `ebook-convert` installation #32 #125

chore(release): v3.6.6

---

packages/@honkit/theme-default/_layouts/website/page.html
packages/@honkit/theme-default/src/js/theme/sidebar.js
packages/@honkit/theme-default/src/less/website/body.less
packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap

fix #91 
We need to research that it has backward compatible.
Preview URL: https://deploy-preview-92--honkit.netlify.app/

perf(default-theme): move restoring sidebar logic to critical path

---

.github/workflows/publish.yml

👷 Migrate set-env to $GITHUB_ENV 

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/book/CHANGELOG.md
examples/book/package.json
lerna.json
packages/@honkit/theme-default/CHANGELOG.md
packages/@honkit/theme-default/_layouts/website/page.html
packages/@honkit/theme-default/package.json
packages/honkit/CHANGELOG.md
packages/honkit/package.json
packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap

Fix a regression of theme-default on v3.6.9 #148 
> Official page is blank on mobile #151 
fix #151

fix(theme-default): fix blank page on mobile

---

docker/Dockerfile
docker/README.md

fix(docker): add calibre tarball

---

packages/honkit/semgrep.yml
packages/honkit/src/cli/getBook.ts
packages/honkit/src/init.ts
packages/honkit/src/models/book.ts
packages/honkit/src/models/output.ts
packages/honkit/src/output/testing/createMock.ts
packages/honkit/src/output/testing/generateMock.ts
packages/honkit/src/parse/__tests__/listAssets.ts
packages/honkit/src/parse/__tests__/parseBook.ts
packages/honkit/src/parse/__tests__/parseGlossary.ts
packages/honkit/src/parse/__tests__/parseIgnore.ts
packages/honkit/src/parse/__tests__/parseReadme.ts
packages/honkit/src/parse/__tests__/parseSummary.ts
packages/honkit/src/parse/parseBook.ts
packages/honkit/tsconfig.json

1. migrate book.ts
```
❯ semgrep --config semgrep.yml ./src/models/book.ts --autofix
```
2. compile TypeScript and fix compile error
https://github.com/honkit/honkit/issues/40#issuecomment-735353069

refactor(honkit): migrate book.ts to class-based immutable model

---

packages/honkit/src/models/__tests__/config.ts
packages/honkit/src/models/book.ts
packages/honkit/src/models/config.ts
packages/honkit/src/models/pluginDependency.ts
packages/honkit/src/modifiers/config/__tests__/addPlugin.ts
packages/honkit/src/modifiers/config/__tests__/removePlugin.ts
packages/honkit/src/modifiers/config/__tests__/togglePlugin.ts
packages/honkit/src/utils/command.ts

refs https://github.com/honkit/honkit/issues/40

refactor(honkit): migrate config.ts to class-based

---

packages/honkit/src/init.ts
packages/honkit/src/models/__tests__/glossary.ts
packages/honkit/src/models/__tests__/summary.ts
packages/honkit/src/models/__tests__/summaryArticle.ts
packages/honkit/src/models/config.ts
packages/honkit/src/models/file.ts
packages/honkit/src/models/fs.ts
packages/honkit/src/models/glossary.ts
packages/honkit/src/models/languages.ts
packages/honkit/src/models/page.ts
packages/honkit/src/models/readme.ts
packages/honkit/src/models/summary.ts
packages/honkit/src/modifiers/summary/__tests__/editPartTitle.ts
packages/honkit/src/modifiers/summary/__tests__/insertArticle.ts
packages/honkit/src/modifiers/summary/__tests__/insertPart.ts
packages/honkit/src/modifiers/summary/__tests__/mergeAtLevel.ts
packages/honkit/src/modifiers/summary/__tests__/moveArticle.ts
packages/honkit/src/modifiers/summary/__tests__/moveArticleAfter.ts
packages/honkit/src/modifiers/summary/__tests__/removeArticle.ts

refs https://github.com/honkit/honkit/issues/40

refactor(honkit): migrate file.ts to class-based model

---

packages/honkit/src/models/__tests__/glossary.ts
packages/honkit/src/models/__tests__/glossaryEntry.ts
packages/honkit/src/models/book.ts
packages/honkit/src/models/glossary.ts
packages/honkit/src/models/glossaryEntry.ts
packages/honkit/src/output/modifiers/__tests__/annotateText.ts
packages/honkit/src/parse/parseGlossary.ts

refs https://github.com/honkit/honkit/issues/169

refactor(honkit): migrate Glossary to class-based model

---

examples/benchmark/package.json
package.json
packages/@honkit/asciidoc/package.json
packages/@honkit/html/package.json
packages/@honkit/internal-test-utils/package.json
packages/@honkit/markdown-legacy/package.json
packages/@honkit/markdown/package.json
packages/@honkit/markup-it/package.json
packages/@honkit/theme-default/package.json
packages/honkit/package.json
packages/honkit/src/bin.ts
yarn.lock

update dev dependencies.
It is Maintainance updates.

chore(deps): update devDeps

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/book/CHANGELOG.md
examples/book/package.json
lerna.json
packages/@honkit/asciidoc/CHANGELOG.md
packages/@honkit/asciidoc/package.json
packages/@honkit/html/CHANGELOG.md
packages/@honkit/html/package.json
packages/@honkit/internal-test-utils/CHANGELOG.md
packages/@honkit/internal-test-utils/package.json
packages/@honkit/markdown-legacy/CHANGELOG.md
packages/@honkit/markdown-legacy/package.json
packages/@honkit/markdown/CHANGELOG.md
packages/@honkit/markdown/package.json
packages/@honkit/markup-it/CHANGELOG.md
packages/@honkit/markup-it/package.json
packages/@honkit/theme-default/CHANGELOG.md
packages/@honkit/theme-default/package.json
packages/honkit/CHANGELOG.md
packages/honkit/package.json

- **honkit**: use ^ semver for deps #185
- **honkit**: update dependencies #181

chore(release): v3.6.17

---

packages/honkit/src/plugins/loadPlugin.ts

info: plugin "highlight is loaded
corrected to..
info: plugin "highlight" is loaded

Update loadPlugin.ts - fix logging output

---

package.json
yarn.lock

It will reduces warnings.
- [Release v4.0.0 · lerna/lerna](https://github.com/lerna/lerna/releases/tag/v4.0.0)

chore(deps): update lerna@4

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/book/CHANGELOG.md
examples/book/package.json
lerna.json
packages/@honkit/theme-default/CHANGELOG.md
packages/@honkit/theme-default/package.json
packages/honkit/CHANGELOG.md
packages/honkit/package.json

* **theme-default:** fix Uncaught TypeError when click a page ([#196](https://github.com/honkit/honkit/issues/196)) ([349aae6](https://github.com/honkit/honkit/commit/349aae6eedac78e21359d1914d4914156e32d1c5)) closes #191

chore(release): v3.6.18

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/book/CHANGELOG.md
examples/book/package.json
lerna.json
packages/@honkit/honkit-plugin-highlight/CHANGELOG.md
packages/@honkit/honkit-plugin-highlight/package.json
packages/honkit/CHANGELOG.md
packages/honkit/package.json

* **honkit-plugin-highlight:** fix highlight.js warning ([#200](https://github.com/honkit/honkit/issues/200)) ([4433488](https://github.com/honkit/honkit/commit/44334889aef22d991529c29ad823c6821f96614c))

chore(release): v3.6.19

---

packages/@honkit/theme-default/src/js/core/page.js

Remove Console Log for Page Changes

---

docker/README.md

Update readme file in the Docker folder to add a new entry.
The input consists of the serve command and the necessary parameters so that docker can be stopped.
The information used for this command has been obtained from [How to stop running node in docker] (https://stackoverflow.com/questions/36637912/how-to-stop-running-node-in-docker).

Update readme file in Docker folder

---

package.json
packages/honkit/src/constants/__tests__/configSchema.ts
packages/honkit/src/parse/validateConfig.ts
packages/honkit/src/plugins/validateConfig.ts
yarn.lock

- update deps
- remove @types/jsonschema that is unnecessary, because jsonschema bundle types

chore(deps): remove @types/jsonschema

---

packages/@honkit/markup-it/README.md

docs(@honkit/markup-it/README.md): s/@honkite/@honkit/g

---

docs/plugins/hooks.md
packages/honkit/src/json/encodePage.ts

- add articles to page object
- add more details to page hooks document 
Related issue: #241

feat: update page object

---

packages/honkit/src/json/encodePage.ts
packages/honkit/src/json/encodeSummaryArticle.ts
packages/honkit/src/json/encodeSummaryArticleWithCache.ts
packages/honkit/src/models/__tests__/summaryArticle.ts

- memorize encoded summary article
https://github.com/honkit/honkit/issues/241#issuecomment-999260192

perf: memorize encoded summary article

---

packages/honkit/package.json
packages/honkit/src/json/encodeSummaryArticleWithCache.ts
yarn.lock

Follow up #243 
use LRU map to avoid memory leak.

refactor: use LRU_MAP

---

.github/workflows/benchmark.yml
.github/workflows/create-release-pr.yml
.github/workflows/publish.yml
.github/workflows/test.yml
packages/@honkit/theme-default/src/js/theme/navigation.js

Fix to replace at once.
Previous:
- Replace both `<html>` and ``
Next:
- Replace first `<html>`
fix #265

fix(theme-default): prevent to replace html/head/body as strings

---

docs/GLOSSARY.md
packages/honkit/src/__tests__/__fixtures__/honkit/docs/GLOSSARY.md
packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
packages/honkit/src/output/__tests__/website.ts

Add GLOSSARY.md to honkit it-self.
It will help to test #281

 docs: add GLOSSARY.md to HonKit documentation 

---

packages/honkit/package.json
yarn.lock

Upgrade juice to 8.x

---

packages/@honkit/theme-default/package.json

fix(theme-default): add --flat to fonts

---

docs/plugins/README.md

Minor spelling improvement.
also mark some json correctly as json.

improve spelling of compatible

---

packages/@honkit/markup-it/README.md
packages/@honkit/markup-it/package.json
packages/@honkit/markup-it/syntaxes/markdown/__tests__/normalizeTeX.spec.js
packages/@honkit/markup-it/syntaxes/markdown/math.js
yarn.lock

remove unmaintain ltrim and rtrim package

refactor: remove ltrim and rtrim

---

docs/examples.md

I have added a book for learning JavaScript that utilizes honkit for content building and publishing.

add learn javascript book

---

packages/@honkit/honkit-plugin-highlight/package.json
packages/@honkit/honkit-plugin-highlight/scripts/build-less.js
packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
yarn.lock

Default theme is a bit change.
Some Language Aliases has been removed.
- [Release Version 11 · highlightjs/highlight.js](https://github.com/highlightjs/highlight.js/releases/tag/11.0.0)
- [highlight.js/VERSION_11_UPGRADE.md at main · highlightjs/highlight.js](https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md)
fix #355

chore(deps): update to highlight.js 11

---

.github/workflows/benchmark.yml
.github/workflows/release.yml
.github/workflows/test.yml
packages/honkit/src/output/modifiers/__tests__/fetchRemoteImages.ts

- fix #361 
- fix #360 
Add Node.js 20 to CI.

feat!(docker): Update to Node.js 18

---

nx.json
package.json
packages/@honkit/markup-it/package.json
packages/honkit/package.json
yarn.lock

chore: add nx cache

---

.editorconfig
eslint.config.mjs
package.json
packages/@honkit/cleaning-tools/README.md
packages/@honkit/cleaning-tools/eslint.config.mjs
packages/@honkit/cleaning-tools/index.mjs
packages/@honkit/cleaning-tools/package.json
packages/@honkit/honkit-plugin-fontsettings/eslint.config.mjs
packages/@honkit/honkit-plugin-fontsettings/package.json
packages/@honkit/markup-it/eslint.config.mjs
packages/@honkit/markup-it/package.json
packages/@honkit/theme-default/eslint.config.mjs
packages/@honkit/theme-default/package.json
pnpm-lock.yaml
prettier.config.mjs

This builds on #442 and may require rebase if that PR is rejected.

Lint format simplify

---

.github/workflows/benchmark.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-release-pr.yml
.github/workflows/release.yml
.github/workflows/test.yml

Pin all actions's version.
```
pinact run -u
```
https://github.com/suzuki-shunsuke/pinact

CI: update  & pin version

---

packages/@honkit/asciidoc/package.json
packages/@honkit/html/src/dom.ts
packages/@honkit/html/src/index.ts
packages/@honkit/html/src/totext.ts
packages/@honkit/markdown-legacy/lib/page.js
packages/@honkit/markdown-legacy/lib/toHTML.js
pnpm-lock.yaml

update lodash imports to specific functions for reduce import costs
remove unused lodash from package

refactor: update lodash imports to specific functions for reduce import costs

---

package.json
pnpm-lock.yaml

update lint-staged from v13 to v16
<https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md>

chore: update lint-staged from v13 to v16

---

packages/@honkit/html/src/summary.ts
packages/@honkit/markup-it/src/parse/textToUnstyledTokens.ts
packages/honkit/src/plugins/package-name-util.ts

simplify for loop syntax to use for...of for better readability

refactor: simplify for loop syntax to use for...of for better readability

---

packages/honkit/src/cli/server.ts
packages/honkit/src/models/pluginDependency.ts
packages/honkit/src/output/generatePages.ts
packages/honkit/src/output/modifiers/__tests__/resolveImages.ts
packages/honkit/src/utils/__tests__/git.ts

refactor: remove unused imports
