- examples/benchmark/resources/gitbook-plugin-include-codeblock.hbs
- packages/@honkit/markdown/src/__tests__/page.js
- packages/@honkit/markup-it/syntaxes/markdown/code.js
This behavior break Fenced code blocks macro like https://github.com/vowstar/gitbook-plugin-uml
- `page:before`: Convert Fenced code blocks to Block Tags that includes Indented CodeBlock
- `plugin.prepare`: Convert Indented CodeBlock to Fenced code blocks <- This break the plugin and This commit fix it
- Convert Block Tags by plugins
This commit remove `plugin.prepare` behavior that convert Indented CodeBlock to Fenced code blocks.
As a result, the plugin receive Indented CodeBlock's content instead of triple tick content.
So, it will make https://github.com/vowstar/gitbook-plugin-uml work in HonKit.
fix #58
> fix(markdown): Do not force convert Indented CodeBlock to Fenced code blocks

- docs/plugins/create.md
- packages/honkit/src/models/__tests__/config.ts
- packages/honkit/src/models/pluginDependency.js
Fix to detect logic about scoped module.
Previously, @scope/honkit-plugin-name is just ignored
This commit fix to load scoped module like `@ansanloms/uml`
- https://github.com/ansanloms/honkit-test
fix #68
> fix(honkit): fix to load @scope/honkit-plugin-name

- .github/workflows/test.yml
- packages/@honkit/markdown-legacy/__tests__/page.js
- packages/@honkit/markdown-legacy/lib/page.js
fix: https://github.com/honkit/honkit/pull/85#discussion_r449770208
> fix(markdown-legacy): normalize some characters for kramed's annotate function

- docs/examples.md
I know this is a small change, but we are happily using honkit for the Arcane Algorithm Archive now. Thanks a bunch for all the great work!
> adding Algorithm Archive to honkit examples

- docs/examples.md
Recently the Django Girls Tutorial converted from Gitbook Legacy to Honkit.
> Add Django Girls Tutorial to examples

- packages/honkit/src/output/modifiers/__tests__/resolveImages.js
- packages/honkit/src/output/modifiers/resolveImages.js
in resolveImages, if src is null or undefined, LocationUtils.toAbsolute occurs error.
This occurs the following content and using gitbook-plugin-changelog.
```
<img
src="....">
```
This file's diff is like the following
```
+<img
+src="...">
```
In this case, resolveImages occurs error  because LocationUtils.toAbsolute used in resolveImages expects src is string.
> return if src is null or undefined in resolveImages

- packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
- packages/honkit/src/models/__tests__/summary.ts
- packages/honkit/src/models/__tests__/summaryArticle.ts
- packages/honkit/src/models/summary.js
- packages/honkit/src/models/summaryArticle.js
When next/prev article has anchor(hello.md#anchor), HonKit navigation will ignore it.
For example, The next of `Markdown` page is `Asciidoc`.
`SUMMARY.md`:
```
* [Markdown](syntax/markdown.md)
* [Headings](syntax/markdown.md#headings)
* [Paragraphs](syntax/markdown.md#paragraphs)
* [Lists](syntax/markdown.md#lists)
* [Asciidoc](syntax/asciidoc.md)
```
Previously, The next of `Markdown` was `Headings`, But it is a bug from original GitBook.
- [Fix to ignore anchor points by mizunashi-mana · Pull Request #1467 · GitbookIO/gitbook](https://github.com/GitbookIO/gitbook/pull/1467)
fix https://github.com/honkit/honkit/issues/109
> fix(honkit): fix next/prev button on anchor article

- .github/workflows/publish.yml
- CHANGELOG.md
- README.md
- examples/benchmark/CHANGELOG.md
- examples/benchmark/package.json
- examples/book/CHANGELOG.md
- examples/book/package.json
- lerna.json
- packages/honkit/CHANGELOG.md
- packages/honkit/package.json
We start to support Docker(basic)
- https://hub.docker.com/r/honkit/honkit
docker pull honkit/honkit
Show help 
$ docker run -v `pwd`:`pwd` -w `pwd` --rm -it honkit/honkit honkit  --help
Build
$ docker run -v `pwd`:`pwd` -w `pwd` --rm -it honkit/honkit honkit build
We need to improve docker support. 
For example, we want to get `ebook-convert` integration for `honkit pdf` or `honkit epub`
refs #32
> v3.6.3: Basic docker support

- CHANGELOG.md
- docker/Dockerfile
- examples/benchmark/CHANGELOG.md
- examples/benchmark/package.json
- examples/book/CHANGELOG.md
- examples/book/package.json
- lerna.json
- packages/honkit/CHANGELOG.md
- packages/honkit/package.json
**Fixes**
- **docker**: use latest as default when build without `--build-arg PACKAGE_VERSION=<v>`
> chore(release): v3.6.4

- CHANGELOG.md
- examples/benchmark/CHANGELOG.md
- examples/benchmark/package.json
- examples/book/CHANGELOG.md
- examples/book/package.json
- lerna.json
- packages/honkit/CHANGELOG.md
- packages/honkit/bin/honkit.js
- packages/honkit/package.json
- packages/honkit/src/bin.ts
- packages/honkit/src/constants/defaultPlugins.ts
- packages/honkit/src/honkit.ts
- packages/honkit/tsconfig.json
In sometimes, CI publish empty content
- 3.6.0 ~ 3.6.4 has a this bug.
tsc copy `package.json` if use `import pkg from "../package.json"`
`npm pack` fail to pack if the package has two package.json
- package.json
- lib
- package.json
npm pack refer to `lib/package.json`. 
It creates an empty pack
https://github.com/honkit/honkit/pull/123/commits/50e8e4c0855dd1784912ebd59915f30f5cdc7dc4
> fix(honkit): fix empty publish

- packages/@honkit/theme-default/src/js/core/index.js
- packages/honkit/src/api/encodeGlobal.ts
- packages/honkit/src/json/encodeBook.ts
- provide `honkit` variables have equivalent ​​values to `gitbook`
variables.
#36
> feat(honkit) support `honkit` variables

- docs/plugins/hooks.md
- packages/honkit/src/output/__tests__/generatePage.ts
- packages/honkit/src/output/__tests__/plugin-hooks.ts
- packages/honkit/src/output/callHook.ts
- packages/honkit/src/output/generateBook.ts
- packages/honkit/src/output/generatePage.ts
- packages/honkit/src/output/generatePages.ts
- packages/honkit/src/output/page-cache.ts
- packages/honkit/src/output/testing/generateMock.ts
- packages/honkit/src/parse/parsePageFromString.ts
- packages/honkit/src/plugins/PluginResolver.ts
- packages/honkit/src/plugins/loadForBook.ts
- tsconfig.json
Previously, skit "page" and "page:before" hook when HonKit has the cache for page.
However, this logic breaks some plugin like lunr plugin.
This PR fixes it.
HonKit always call `"page"` and `"page:before"`.
fix https://github.com/honkit/honkit/issues/137
> fix(honkit): fix cache algorithm

- CHANGELOG.md
- examples/benchmark/CHANGELOG.md
- examples/benchmark/package.json
- examples/book/CHANGELOG.md
- examples/book/package.json
- lerna.json
- packages/@honkit/theme-default/CHANGELOG.md
- packages/@honkit/theme-default/package.json
- packages/honkit/CHANGELOG.md
- packages/honkit/package.json
- packages/honkit/tsconfig.json
- tsconfig.json
- [Bug: ignore "page" hook of plugin when cache is enabled · Issue #137 · honkit/honkit](https://github.com/honkit/honkit/issues/137)
Previously, skip "page" and "page:before" hook when HonKit has the cache for the page.
However, this logic breaks some plugin like [plugin-lunr](https://github.com/GitbookIO/plugin-lunr).
In 3.6.8, HonKit always call `"page"` and `"page:before"`.
> chore(release): v3.6.8

- docs/plugins/testing.md
[honkit-tester](https://github.com/vowstar/honkit-tester) : over time, for plugin testing, in some cases gitbook-tester no longer works properly on the latest version of nodejs. This is a port of gitbook-tester, which could works on LTS version of nodejs v10 v12 v14, and using the honkit engine instead of gitbook to run test.
> docs/plugins/testing.md: add honkit-tester

- packages/honkit/src/parse/__tests__/listAssets.ts
- packages/honkit/src/parse/listAssets.ts
fs.listallFiles returns paths that use '\\' as a path separator on Windows.
`pages` object includes paths that use '/' as a path separator.
So replace all '\\' of path in function filterFile()
fix #146
> fix (parse/listAssets.ts): fix issue #146

- CHANGELOG.md
- examples/benchmark/CHANGELOG.md
- examples/benchmark/package.json
- examples/book/CHANGELOG.md
- examples/book/package.json
- lerna.json
- packages/@honkit/theme-default/CHANGELOG.md
- packages/@honkit/theme-default/package.json
- packages/honkit/CHANGELOG.md
- packages/honkit/package.json
No changes from v3.6.10.
It only includes fixing CI error #149 
It aims to publish a new docker image.
> chore(release): v3.6.11

- packages/honkit/src/__tests__/__fixtures__/honkit/docs/SUMMARY.md
- packages/honkit/src/__tests__/__fixtures__/honkit/docs/encoding.md
- packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
- packages/honkit/src/output/modifiers/modifyHTML.ts
Non-ASCII charcters of  output html files are escaped.
This PR do replace all `&#x<4 hex diigits>;` to unescaped charctares.
As a result, this PR requires update of snapshot.
Close Issue #87
> fix (output/modifiers): unescape characteres of output html

- packages/@honkit/theme-default/src/less/website/body.less
- packages/@honkit/theme-default/src/less/website/header.less
- packages/@honkit/theme-default/src/less/website/navigation.less
- packages/@honkit/theme-default/src/less/website/summary.less
While Honkit has a dedicated `print` command to generate the entire book, users also expect to be able to print a specific page with their browser's "Print" feature. This doesn't currently look great because of a few minor CSS issues.
**Before:**
**After:**
> Fix browser print layout in default theme

- packages/@honkit/theme-default/_layouts/layout.html
- packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
`theme-default` uses the following meta tags in layout.html
```html
<meta charset="UTF-8">                                                 
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">    
```
Regarding this, the first one seems to be enough for HTML5.
The PR aims to suppress a warning from [tidy](https://www.html-tidy.org/)
```
line 6 column 9 - Warning: discarding unexpected <meta>
```
```html
1:
2:<!DOCTYPE HTML>
3:<html lang="" >
4:    <head>
5:        <meta charset="UTF-8">
6:        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
```
__Background__
I'm using  HTML tags in my HonKit project, so it's inevitable to check HTML validity before publishing a book.
> fix (theme/default): remove unnecessary meta tag

- packages/@honkit/theme-default/src/js/theme/navigation.js
Currently, click body and throw an Error.
```
Uncaught TypeError: ((ke.event.special[i.origType] || {}).handle || i.handler).apply is not a function
at HTMLDivElement.dispatch (theme.js:2)
at HTMLDivElement.v.handle (theme.js:2)
```
This PR fixes it.
use native `.focus({ preventScroll :true })` instead of jQuery.
It seems that jQuery does not support  `preventScroll`.
- [jQuery focus without scroll - Stack Overflow](https://stackoverflow.com/questions/4898203/jquery-focus-without-scroll)
fix https://github.com/honkit/honkit/issues/191
refs https://github.com/honkit/honkit/issues/135
> fix(theme-default): fix Uncaught TypeError when click a page

- packages/@honkit/honkit-plugin-highlight/index.js
- packages/@honkit/honkit-plugin-highlight/package.json
- yarn.lock
Fix a warning
```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```
fix https://github.com/honkit/honkit/issues/199
refs https://github.com/highlightjs/highlight.js/issues/2277
> fix(honkit-plugin-highlight): fix highlight.js warning

- packages/honkit/src/output/ebook/getPDFTemplate.ts
Possible fix for https://github.com/honkit/honkit/issues/236
> Replace newlines with white space in pdf headers + footers

- packages/honkit/src/cli/watch.ts
Prevent infinitely reload.
fix https://github.com/honkit/honkit/issues/269
> fix(honkit): hokit server should not watch node_modules/** changes

- packages/@honkit/theme-default/package.json
Without this, an additional `logo` directory is created leading to a broken reference.
https://github.com/sindresorhus/cpy-cli/pull/34
https://github.com/sindresorhus/cpy/releases/tag/v9.0.0
> Fix missing --flat for cpy 9+

- packages/honkit/src/utils/fs.ts
Just a quick PR to fix #285 :)
> Replace deprecated `fs.rmdir` with `fs.rm`

- docs/plugins/testing.md
Because the test component is updated, the supported node version has changed
> docs/plugins/testing.md: bump honkit-tester supported node version

- docs/README.md
Also use semantic line breaks to make lines shorter and diffs cleaner.
See https://rhodesmill.org/brandon/2012/one-sentence-per-line/ for more info.
> Link to gitbook comparison in home page

- packages/honkit/src/cli/serve.ts
- packages/honkit/src/models/book.ts
Show warning message instead of process exiting.
```
$ yarn run honkit:serve --reload
yarn run v1.22.19
$ honkit serve --reload
Live reload server started on port: 35729
Press CTRL+C to quit ...
info: >> Starting server ...
info: >> Clear cache
info: 3 plugins are installed
info: 3 explicitly listed
info: plugin "@honkit/honkit-plugin-theme" is loaded
info: plugin "livereload" is loaded
info: plugin "highlight" is loaded
info: found 23 pages
info: found 0 asset files
info: >> generation finished with success in 0.7s !
Serving book on http://localhost:4000
warn: >> /Users/azu/ghq/github.com/honkit/honkit/docs/config.md does not exist in file system.
```
fix #372 
---
`honkit serve`でwatchしてるファイルを削除すると、プロセスが終了する問題を修正するPRです。
cc @misaki-s
> fix(honkit): honkit serve should not exit when watched file is deleted

- docs/plugins/api.md
Fix broken link.
Also, Deprecate `Output` APIs.
This just exposes the model to the outside world, which is not a good API.
fix #377
> docs(api): fix link

- docs/plugins/api.md
The display on [this page](https://honkit.netlify.app/plugins/api) is corrupted due to incorrect markdown and unnecessary characters.
> docs(api.md): fix typo

- .github/workflows/test.yml
- docker/Dockerfile
Fixed a crash in Docker Image `honkit/honkit:v5` with commands that use calibre such as `honkit pdf`, and added Docker Image behavior testing, including Dockerfile refactoring and calibre.
1. Add Docker Image build and pdf generation from build result to CI as a test
* We can see how the pdf generation is failing before the fix from [here](https://github.com/KentarouTakeda/honkit-honkit/actions/runs/7335808647/job/19974218986) in my repository.
* We can confirm that there is no problem after this fix from the CI of this Pull Request.
* If it is difficult to maintain, feel free delete this test. (Or you can mention me if this test breaks)
2. Modifying dependent packages by updating the base image OS version
* Base Image has been changed from `debian:10` to `debian:12` on `node:18`. The …
> Fixed calibre crash when using Docker Image

- packages/honkit/src/cli/buildEbook.ts
- packages/honkit/src/fs/tmpdir.ts
- packages/honkit/src/utils/fs.ts
ebook-convert can not resolve symlink path.
This PR fix following error on `ebook-convert` by passsing real path(= /private/var).
```
Not adding /private/var/folders/44/kk91lr2j0pb00nd4d6m78_v00000gn/T/tmp-70306hObyoPSI8oD3/docs/assets/newplot.png as it is outside the document root: /var/folders/44/kk91lr2j0pb00nd4d6m78_v00000gn/T/tmp-70306hObyoPSI8oD3/
````
- fix #394
> fix(honkit): use real path for tmp dir

- .github/workflows/test.yml
Disable these tests due to apparent networking issues in the tests.
> chore(test): disable Node 16/18 tests on Windows

- packages/@honkit/markdown/src/__tests__/page.ts
- packages/@honkit/markup-it/syntaxes/markdown/__tests__/specs/main.html
- packages/@honkit/markup-it/syntaxes/markdown/__tests__/specs/main.md
- packages/@honkit/markup-it/syntaxes/markdown/document.js
The markup-it syntax parser for markdown now coerces a trailing double space to a <br> tag to provide the expected line break behavior. Tests have been added as well.
Closes #420
> fix(markdown): convert trailing spaces to <br>

- netlify.toml
Netlify cache with Nx is broken.
https://answers.netlify.com/t/support-guide-nx-monorepo-site-does-not-reflect-changes-after-build/73657
This PR clear netlify cache before building as workaround
> CI(netlify): add NX_SKIP_NX_CACHE=true

- CHANGELOG.md
- docs/SUMMARY.md
Points the documentation link to the GitHub releases page and adds a deprecation notice and link to the top of the old changelog file as it is out of date and a duplicate effort.
> docs(changelog): point to releases for changelog

- packages/honkit/package.json
- packages/honkit/src/plugins/PluginResolver.ts
- packages/honkit/src/utils/path.ts
- pnpm-lock.yaml
Remove deprecated try-resolve and directly implement.
Closes #457.
> refactor: remove try-resolve dependency and implement custom path utility

- CONTRIBUTING.md
- docs/syntax/asciidoc.md
- docs/syntax/markdown.md
- docs/templating/README.md
correct typos in documentation files
> chore: correct typos in documentation files

- packages/@honkit/html/package.json
- pnpm-lock.yaml
> chore: remove unused 'q' dependency

- .github/workflows/release.yml
- package.json
This PR updates the release workflow to properly support npm OIDC (OpenID Connect) publishing without long-lived tokens.
- Added `environment: npm` to the release job for OIDC authentication  
- Separated build and publish into distinct workflow steps for better clarity
- Removed unused `release` script from package.json (releases are only done via CI)
- Use npm commands directly in the workflow for publishing with provenance
Part of the migration to npm trusted publishing with OIDC.
> fix: update release workflow for npm OIDC publishing
